name: generate-pdf

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-pdf-missing-in-commit:
    runs-on: ubuntu-latest
    outputs:
      pdf_missing: ${{ steps.check-pdf-missing.outputs.pdf_missing }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check PDF missing in commit
        id: check-pdf-missing
        run: |
          git show --name-status --pretty="" | grep "\.pdf$"
          pdf_missing=$([ $? -eq 0 ] && echo 'false' || echo 'true')
          echo "pdf_missing=${pdf_missing}" >> "$GITHUB_OUTPUT"

  generate-pdf:
    runs-on: ubuntu-latest
    needs: check-pdf-missing-in-commit
    if: needs.check-pdf-missing-in-commit.outputs.pdf_missing == 'true'
    env:
      DISPLAY: ':99.0'
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen

      - name: Install dependencies
        run: npm clean-install --omit=dev --ignore-scripts

      - name: Electron install workaround
        run: |
          # Workaround "Electron failed to install correctly" error
          cd node_modules/electron \
          && node install.js

      - name: Setup graphical environment
        run: |
          sudo apt-get install xvfb
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Generate PDF
        run: npm run pdf

      - name: Commit PDF
        run: |
          git config user.name '${{ vars.GIT_NAME }}'
          git config user.email ${{ vars.GIT_EMAIL }}
          git add *.pdf
          git commit -m "Automated PDF update"
          git push
